### ISSUE TITLE
Start New Search error

### ISSUE THREAD

**Issue by nathankota** [agrc/deq-enviro#581]
This seems to happen randomly, so I cannot reproduce it regularly; and I forgot to click on `Show technical details 🤓` to see what information is there, but maybe this can be a placeholder issue for future errors.

After performing an advanced search, when I click `Start New Search` I sometimes get the error page:
 
![image](https://github.com/agrc/deq-enviro/assets/15659642/2376b278-81c1-464d-a83f-793efda6e7b3)

**Comment by stdavis** [comment]
@nathankota I'm unable to reproduce this. I have made improvements to the logic related to the search wizard since this issue was opened. Perhaps it's fixed?

**Comment by nathankota** [comment]
I did a statewide search of four point layers to test #574. One layer was `Oil and Gas - Wells`, which resulted in a Failed to fetch error. I navigated around the page, clicked on some points, then let the page sit for several minutes while I did some other things. When I came back to it and clicked `Start New Search` I got the error page. Clicking on `Show technical details` resulted in:

_TypeError: Cannot read properties of null (reading 'indexOf')
    at https://enviro.dev.utah.gov/assets/index-HfvjSQHl.js:4964:15389
    at gO (https://enviro.dev.utah.gov/assets/index-HfvjSQHl.js:40:24328)
    at h_ (https://enviro.dev.utah.gov/assets/index-HfvjSQHl.js:40:42530)
    at jRe (https://enviro.dev.utah.gov/assets/index-HfvjSQHl.js:40:41350)
    at Qm (https://enviro.dev.utah.gov/assets/index-HfvjSQHl.js:40:40387)
    at sZ (https://enviro.dev.utah.gov/assets/index-HfvjSQHl.js:40:36975)
    at vm (https://enviro.dev.utah.gov/assets/index-HfvjSQHl.js:38:3292)
    at https://enviro.dev.utah.gov/assets/index-HfvjSQHl.js:40:34339_

@stdavis I'm okay with closing this issue if there is nothing you can think to do about it at the moment. When I tried to replicate the query and error, I was not able to. Let me know what you think.

**Comment by stdavis** [comment]
From Nathan:
>I keep getting the Something went wrong error, again after letting it sit for a while after doing statewide Public Water System Facilities search.

A "while" means a few minutes.
